In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = sns.load_dataset("iris")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [8]:
X = df.drop("species", axis = 1)
y = df["species"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred)

['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa'
 'setosa' 'setosa' 'setosa' 'virginica' 'virginica' 'versicolor'
 'versicolor' 'virginica' 'setosa' 'virginica' 'setosa' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'setosa' 'setosa' 'virginica' 'versicolor'
 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'setosa']


In [9]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [10]:
correct_pred = np.trace(cm)
total_pred = np.sum(cm)
wrong_pred = total_pred - correct_pred

print(f"Correct predictions: {correct_pred: .2f}")
print(f"Wrong predictions: {wrong_pred: .2f}")

Correct predictions:  44.00
Wrong predictions:  1.00


In [11]:
acc = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average = 'macro')
recall = recall_score(y_test, y_pred, average = 'macro')
error = 1 - acc

print(f"Accuracy is: {acc: .2f}")
print(f"Recall is: {recall: .2f}")
print(f"Precision is: {precision: .2f}")
print(f"Error rate is: {error: .2f}")

Accuracy is:  0.98
Recall is:  0.97
Precision is:  0.98
Error rate is:  0.02
